the_weather/urls.py
from the_weather import views
from django.urls import path

app_name = 'the_weather'

urlpatterns = [
    path('', views.index, name='home'),
    path('<city_name>/delete', views.delete, name='delete'),
]

weather/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('weather/', include('the_weather.urls')),
]

the_weather/models.py
from django.db import models

class City(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

the_weather/forms.py
from .models import City
from django.forms import ModelForm, TextInput

class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ['name']
        widgets = {'name': TextInput(attrs={'class': 'input', 'placeholder': 'City'})}

the_weather/views.py
import requests
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import City
from .forms import CityForm

def index(request):
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=metric&appid=d2ad988e3aea888bca35fc4b05349dd6'
    # datetime module is a class, x is its object

    if request.method == "POST":

        # if form.is_valid():
        new_city = request.POST['name']
        r = requests.get(url.format(new_city)).json()
        # city is a match, success 200, checking it in the response 'r' obj
        if r['cod'] == 200:
            if City.objects.filter(name=new_city).exists():
                messages.info(request, 'City exists')
            else:
                form = CityForm(request.POST)
                form.save()
                return redirect('the_weather:home')

        # if city is not a valid city( ie cod = 404)
        else:
            messages.info(request, 'Invalid City')

    # else display all saved city weather
    all_city = City.objects.all()

    # adding all cities with weather detail to this list
    weather_list = []
    for city in all_city:
        r = requests.get(url.format(city)).json()

        city_weather = {
            'city': city,
            'temperature': r['main']['temp'],
            'description': r['weather'][0]['description'],
            'icon': r['weather'][0]['icon'],
        }

        # appending city weather for all the city objects to a list
        # so that we can display that list on the homepage, BY LOOPING OVER IN INDEX.HTML
        weather_list.append(city_weather)

    # if request is GET
    form = CityForm()

    context = {'weather_list': weather_list}
    return render(request, 'the_weather/index.html', context=context)


def delete(request, city_name):
    City.objects.get(name=city_name).delete()
    return redirect('the_weather:home')

the_weather/templates/the_weather/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Weather</title>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'the_weather/style.css' %}"/>

    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;500&display=swap" rel="stylesheet">

</head>


<body>

    <!-- search place form-->
    <form action="{% url 'the_weather:home' %}" method="post">
        {% csrf_token %}

        <div class="input">
            <div class="search">
                <input type="text" name="name" id="name" placeholder="City name" required/>
                {{ form.name }}
            </div>

            <div class="btn-block">
                <button type="submit" name="action">Add</button>
            </div>
        </div>
    <!-- to display errors -->
        <div>
            {% for message in messages %}
                <h4> {{ message }} </h4>
            {% endfor %}
        </div>
    </form>
    <!--weather widget-->
    {% for city in weather_list %}
        <div class="widget">

            <div class="left-panel panel">
                <div class="city">
                    {{ city.city }}
                </div>
                <div class="temp">
                   <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="" width="60">
                   {{ city.temperature }}&deg;
                </div>
            </div>
            <div class="right-panel panel">
                <div class="description">
                    {{ city.description }}
                </div>
                <a href="{% url 'the_weather:delete' city.city %}"> Delete </a>
            </div>

        </div>
    {% endfor %}

</body>
</html>